markdown: rdiscount
pygments: true

auto: false
server: false
server_port: 4000

lsi: true

# Folders and files to ignore when compiling the site.
exclude: [bin, Gemfile, Gemfile.lock, README.md]

# Size limit for the quotes.
text_size_limit: 1000