markdown: rdiscount
pygments: true

auto: false
server: false
server_port: 4000

lsi: false

# Folders and files to ignore when compiling the site.
exclude: [Gemfile, Gemfile.lock, README.md]

# Configuration for the quotes page.
text_size_limit: 1000
tumblr_account: "turing-machine"
tumblr_quotes_layout: "default"